{% set name = "brainreg-segment" %}
{% set version = "0.2.20" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/brainreg-segment-{{ version }}.tar.gz
  sha256: 71b25393d77b1d99e0456793b436d8bc4c28645511e8f8903535da1dc331315e

build:
  entry_points:
    - brainreg-segment = brainreg_segment.segment:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.8,<3.11
    - setuptools
    - setuptools-scm
  run:
    - bg-atlasapi  # Imported in source but not declared as requirement
    - brainglobe-napari-io >=0.3.0
    - brainglobe-utils >=0.2.7
    - dask-core >=2.15.0
    - imio
    - napari >=0.4.5
    - napari-plugin-engine >=0.1.4
    - numpy
    - pandas
    - python >=3.8,<3.11
    - pytables
    - qtpy  # Imported in source but not declared as requirement
    - scikit-image
    - scipy  # Imported in source but not declared as requirement
    - tifffile  # Imported in source but not declared as requirement

test:
  imports:
    - brainreg_segment
  commands:
    - pip list
    - pip check
  requires:
    - pip

about:
  home: https://brainglobe.info/
  dev_url: https://github.com/brainglobe/brainreg-segment
  summary: Manual segmentation of 3D brain structures in a common anatomical space
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - adamltyson
    - goanpeca
    - jaimergp
