{% set name = "brainreg-segment" %}
{% set version = "0.2.19" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/brainreg-segment-{{ version }}.tar.gz
  sha256: 0e641ae937a37bd8674290cd5bddfa87599b71a827ff882ca3e81fdf56c6f454

build:
  entry_points:
    - brainreg-segment = brainreg_segment.segment:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.7
    - setuptools
    - setuptools_scm
  run:
    - brainglobe-napari-io
    - dask-core >=2.15.0
    - imio
    - brainglobe-utils
    - napari >=0.4.5
    - napari-plugin-engine >=0.1.4
    - numpy
    - pandas
    - python >=3.7
    - scikit-image
    - pytables

test:
  imports:
    - brainreg_segment
  commands:
    - pip list
    - pip check
  requires:
    - pip

about:
  home: https://brainglobe.info/
  dev_url: https://github.com/brainglobe/brainreg-segment
  summary: Manual segmentation of 3D brain structures in a common anatomical space
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - adamltyson
    - goanpeca
    - jaimergp
